# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
# https://copier.readthedocs.io/en/stable/updating/#never-change-the-answers-file-manually
_commit: v0.0.9-21-g9e38a74
_src_path: gh:FallingColors/hexdummy
advanced: true
capitalize_platforms: true
classname: HexJs
default_branch: main
description: HexJs addon for Hex Casting
display_name: HexJs
github_repo: hexjs
github_user: Master_Bw3
homepage_url: https://master_bw3.github.io/hexjs
java_version: 17
kotlin: true
mappings_name: Yarn
minecraft_version: 1.20.1
mod_version: 0.1.0
modid: hexjs
package: io.github.master_bw3.hexjs
sources_url: https://github.com/Master_Bw3/hexjs
