author: Master_Bw3
book_id: "hexjs:hexjsbook"
default_branch: main
github_repo: hexjs
gradle_mod_version_key: modVersion
hexdoc_mod_plugin_classname: HexJsModPlugin
hexdoc_plugin_classname: HexJsPlugin
java_lang:
  ext: java
  src: java
java_package: io/github/master_bw3/hexjs
mod_display_name: HexJs
modid: hexjs
multiloader: true
pages_url: https://master_bw3.github.io/hexjs
pattern_regex:
  regex: '(?P<is_per_world>register|registerPerWorld)\(HexPattern\.fromAngles\("(?P<signature>[qweasd]+)",\s*HexDir\.(?P<startdir>\w+)\),\s*"(?P<name>[^"]+)"?'
  per_world_value: registerPerWorld
pattern_registry: registry/HexJsPatterns.java
